[package]
name = "generating_random"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.12"
rand = "0.5"
log = "0.4"
env_logger = "0.5"
clap = "2.32"
dotenv = "0.13"
